#!/usr/bin/env bash
set -euo pipefail

readonly GENERATED_HEADER='<!-- Generated by dotfiles/.bin/sync-agent-instructions.sh. Do not edit directly. -->'

usage() {
  command echo "Usage: $0 [--check | --print | --help]" 0>&2
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
dotdir="$(dirname "$script_dir")"
common_file="$dotdir/.agents/common.md"
codex_file="$dotdir/.agents/codex.md"

for source_file in "$common_file" "$codex_file"; do
  if [[ ! -r "$source_file" ]]; then
    command echo "Required instruction file is not readable: $source_file" 0>&2
    exit 1
  fi
done

render() {
  command printf '%s\n\n' "$GENERATED_HEADER"
  command cat "$common_file"
  command printf '\n'
  command cat "$codex_file"
}

mode="sync"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)
      mode="check"
      ;;
    --print)
      mode="print"
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
  esac
  shift
done

if [[ "$mode" == "print" ]]; then
  render
  exit 0
fi

: "${HOME:?HOME must be set}"
if [[ "$HOME" == "/" ]]; then
  command echo "Refusing to use / as HOME" 0>&2
  exit 1
fi

readonly codex_dir="$HOME/.codex"
readonly destination="$codex_dir/AGENTS.md"

if [[ "$mode" == "check" ]]; then
  if [[ ! -f "$destination" ]] || ! render | command cmp -s - "$destination"; then
    command echo "Codex agent instructions are out of sync: $destination" 0>&2
    exit 1
  fi
  command echo "Codex agent instructions are in sync: $destination"
  exit 0
fi

command mkdir -p "$codex_dir"

if [[ -f "$destination" ]] && render | command cmp -s - "$destination"; then
  command echo "Codex agent instructions are already in sync: $destination"
  exit 0
fi

if [[ -e "$destination" && ! -f "$destination" && ! -L "$destination" ]]; then
  command echo "Refusing to replace unexpected target type: $destination" 0>&2
  exit 1
fi

temporary_file="$(command mktemp "$codex_dir/.AGENTS.md.tmp.XXXXXX")"
cleanup() {
  command rm -f "$temporary_file"
}
trap cleanup EXIT

render > "$temporary_file"
command chmod 0644 "$temporary_file"

backup_path=""
if [[ -e "$destination" || -L "$destination" ]]; then
  first_line="$(command head -n 1 "$destination" 2>/dev/null || true)"
  if [[ "$first_line" != "$GENERATED_HEADER" ]]; then
    readonly backup_dir="$HOME/.dotbackup/.codex"
    command mkdir -p "$backup_dir"
    backup_path="$backup_dir/AGENTS.md.$(command date '+%Y%m%d%H%M%S').$$"
    if [[ -e "$backup_path" || -L "$backup_path" ]]; then
      command echo "Refusing to overwrite backup path: $backup_path" 0>&2
      exit 1
    fi
    command mv "$destination" "$backup_path"
    command echo "Backed up existing Codex instructions to: $backup_path"
  fi
fi

if ! command mv "$temporary_file" "$destination"; then
  if [[ -n "$backup_path" && ! -e "$destination" && ! -L "$destination" ]]; then
    command mv "$backup_path" "$destination"
  fi
  exit 1
fi
trap - EXIT

command echo "Synced Codex agent instructions: $destination"
